<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Exam_Portal.Application\Exam_Portal.Application.csproj" />
    <ProjectReference Include="..\Exam_Portal.Core\Exam_Portal.Core.csproj" />
    <ProjectReference Include="..\Exam_Portal.Infrastructure\Exam_Portal.Infrastructure.csproj" />
  </ItemGroup>

</Project>
